[package]
name = "rutendar"
version = "0.7.2"
edition = "2024"

[[bin]]
name = "rr"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["clock", "serde"] }
crossterm = "0.28"
ratatui = "0.29"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
unicode-width = "0.2"

