use super::state::View;

#[derive(Debug, Clone)]
pub enum Action {
    Quit,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    Open,
    Back,
    Create,
    Edit,
    Delete,
    ChangeImportance,
    OpenAgenda,
    OpenUpcoming,
    SwitchView(View),
    GoToToday,
    StartGotoDate,
    Help,
    OpenLink,
    CopyLink,
    ToggleFocus,
    StartSearch,
    Input(char),
    Backspace,
    NextField,
    PreviousField,
    AdjustLeft,
    AdjustRight,
    Submit,
    Confirm(bool),
    ChooseOccurrence,
    ChooseSeries,
    CycleDateFilter,
    CycleItemType,
    CycleImportanceFilter,
    CycleSort,
    ToggleTagMatching,
    PreviousTagFilter,
    NextTagFilter,
    ToggleTagFilter,
    Noop,
}
